app:
    resource: "@AppBundle/Controller/"
    type:     annotation
index:
    pattern:   /
    defaults:  { _controller: AppBundle:Default:index }

new:
    pattern:   /newaction
    defaults:  { _controller: AppBundle:TParametros:index }
calendar:
    pattern:   /calendar
    defaults:  { _controller: AppBundle:Default:AfterLogin }
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
sonata_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_security_2.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin