services:
    app.admin.t_modelosresultados:
        class: AppBundle\Entity\TModelosresultadosAdmin
        arguments: [~, AppBundle\Entity\TModelosresultados, AppBundle:TModelosresultadosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Modelo de Resultados}

    app.admin.t_areasensaio:
        class: AppBundle\Entity\TAreasensaioAdmin
        arguments: [~, AppBundle\Entity\TAreasensaio, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TAreasensaio}

    app.admin.t_estados:
        class: AppBundle\Entity\TEstadosAdmin
        arguments: [~, AppBundle\Entity\TEstados, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TEstados}

    app.admin.t_familiasparametros:
        class: AppBundle\Entity\TFamiliasparametrosAdmin
        arguments: [~, AppBundle\Entity\TFamiliasparametros, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TFamiliasparametros}

    app.admin.t_frascos:
        class: AppBundle\Entity\TFrascosAdmin
        arguments: [~, AppBundle\Entity\TFrascos, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TFrascos}

    app.admin.t_laboratorios:
        class: AppBundle\Entity\TLaboratoriosAdmin
        arguments: [~, AppBundle\Entity\TLaboratorios, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TLaboratorios}

    app.admin.t_metodos:
        class: AppBundle\Entity\TMetodosAdmin
        arguments: [~, AppBundle\Entity\TMetodos, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TMetodos}

    app.admin.t_modelosparametro:
        class: AppBundle\Entity\TModelosparametroAdmin
        arguments: [~, AppBundle\Entity\TModelosparametro, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TModelosparametro}

    app.admin.t_modelosparametrosgrupo:
        class: AppBundle\Entity\TModelosparametrosgrupoAdmin
        arguments: [~, AppBundle\Entity\TModelosparametrosgrupo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TModelosparametrosgrupo}

    app.admin.t_parametros:
        class: AppBundle\Entity\TParametrosAdmin
        arguments: [~, AppBundle\Entity\TParametros, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TParametros}

    app.admin.t_regrasformatacao:
        class: AppBundle\Entity\TRegrasformatacaoAdmin
        arguments: [~, AppBundle\Entity\TRegrasformatacao, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TRegrasformatacao}

    app.admin.t_tecnicas:
        class: AppBundle\Entity\TTecnicasAdmin
        arguments: [~, AppBundle\Entity\TTecnicas, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TTecnicas}

    app.admin.t_tiposarredondamento:
        class: AppBundle\Entity\TTiposarredondamentoAdmin
        arguments: [~, AppBundle\Entity\TTiposarredondamento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TTiposarredondamento}

    app.admin.t_amostras:
        class: AppBundle\Entity\TAmostrasAdmin
        arguments: [~, AppBundle\Entity\TAmostras, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TAmostras}

    app.admin.t_unidadesmedida:
        class: AppBundle\Entity\TUnidadesmedidaAdmin
        arguments: [~, AppBundle\Entity\TUnidadesmedida, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TUnidadesmedida}

    app.admin.t_clientes:
        class: AppBundle\Entity\TClientesAdmin
        arguments: [~, AppBundle\Entity\TClientes, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TClientes}

    app.admin.t_gruposparametros:
        class: AppBundle\Entity\TGruposparametrosAdmin
        arguments: [~, AppBundle\Entity\TGruposparametros, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TGruposparametros}

    app.admin.t_legislacao:
        class: AppBundle\Entity\TLegislacaoAdmin
        arguments: [~, AppBundle\Entity\TLegislacao, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TLegislacao}

    app.admin.t_modelosamostra:
        class: AppBundle\Entity\TModelosamostraAdmin
        arguments: [~, AppBundle\Entity\TModelosamostra, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TModelosamostra}

    app.admin.t_produtos:
        class: AppBundle\Entity\TProdutosAdmin
        arguments: [~, AppBundle\Entity\TProdutos, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TProdutos}

    app.admin.t_tipoaprovacao:
        class: AppBundle\Entity\TTipoaprovacaoAdmin
        arguments: [~, AppBundle\Entity\TTipoaprovacao, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TTipoaprovacao}

    app.admin.t_tiposamostra:
        class: AppBundle\Entity\TTiposamostraAdmin
        arguments: [~, AppBundle\Entity\TTiposamostra, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TTiposamostra}

    app.admin.t_tiposcontrolo:
        class: AppBundle\Entity\TTiposcontroloAdmin
        arguments: [~, AppBundle\Entity\TTiposcontrolo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: TTiposcontrolo}
