parametros:
    type:    rest
    prefix:  /v1
    resource: AppBundle\Controller\TParametrosApiController
    name_prefix:  api_1_ # naming collision

#comments:
#    type:     rest
#    parent:   users
#    resource: Acme\HelloBundle\Controller\CommentsController
